//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;a&quot;:&quot;&quot;,&quot;abandon&quot;:&quot;&quot;,&quot;ability&quot;:&quot;&quot;,&quot;able&quot;:&quot;&quot;,&quot;abortion&quot;:&quot;&quot;,&quot;about&quot;:&quot;&quot;,&quot;above&quot;:&quot;&quot;,&quot;abroad&quot;:&quot;&quot;,&quot;absence&quot;:&quot;&quot;,&quot;absolute&quot;:&quot;&quot;,&quot;absolutely&quot;:&quot;&quot;,&quot;absorb&quot;:&quot;&quot;,&quot;abuse&quot;:&quot;&quot;,&quot;academic&quot;:&quot;&quot;,&quot;accept&quot;:&quot;&quot;,&quot;access&quot;:&quot;&quot;,&quot;accident&quot;:&quot;&quot;,&quot;accompany&quot;:&quot;&quot;,&quot;accomplish&quot;:&quot;&quot;,&quot;according&quot;:&quot;&quot;,&quot;account&quot;:&quot;&quot;,&quot;accurate&quot;:&quot;&quot;,&quot;accuse&quot;:&quot;&quot;,&quot;achieve&quot;:&quot;&quot;,&quot;achievement&quot;:&quot;&quot;,&quot;acid&quot;:&quot;&quot;,&quot;acknowledge&quot;:&quot;&quot;,&quot;acquire&quot;:&quot;&quot;,&quot;across&quot;:&quot;&quot;,&quot;act&quot;:&quot;&quot;,&quot;action&quot;:&quot;&quot;,&qu....
        /// </summary>
        internal static string defaultDictionary {
            get {
                return ResourceManager.GetString("defaultDictionary", resourceCulture);
            }
        }
    }
}
